import Aesop
import Duck.Math.CommutativeAlgebra.Ring
import Duck.Math.CategoryTheory
open Math.CategoryTheory

namespace Math.CommutativeAlgebra

-- The type of modules over a given ring $R$.
axiom Module (R : Ring) : Type
axiom ModuleHom {R : Ring} (M N : Module R) : Type

-- Category structure
instance (R : Ring) : Category (Module R) where
  Hom := ModuleHom
  id := sorryAx
  comp := sorryAx
  comp_assoc := sorryAx
  comp_id := sorryAx
  id_comp := sorryAx

variable {R : Ring}

def Submodule (M : Module R) := Subobject M
axiom kernel {M N : Module R} (f : M ⟶ N) : Submodule M
axiom image {M N : Module R} (f : M ⟶ N) : Submodule N

@[aesop 99%] axiom module_of_ring_hom {R S : Ring} (f : R ⟶ S) : Module R
@[aesop 99%] noncomputable def module_self (R : Ring) := module_of_ring_hom (𝟙 R)

namespace Module
variable {R : Ring}
-- An $R$-module $M$ is finitely generated if there exist elements $m_1, m_2, \ldots, m_n \in M$ (called generators) such that \[ M = R m_1 + R m_2 + \cdots R m_n . \]
axiom finitely_generated (M : Module R) : Prop
-- An $R$-module $M$ is cyclic if it can be generated by one element, that is $M = R m$ for some $m \in M$.
axiom cyclic (M : Module R) : Prop
-- An $R$-module $M$ is free if it is isomorphic to a direct sum $\bigoplus_{i \in I} R$ for some indexing set $I$.
axiom free (M : Module R) : Prop
-- An $R$-module $M$ is projective if the functor $\Hom_R(M, -)$ is exact.
axiom projective (M : Module R) : Prop
-- An $R$-module $M$ is injective if the functor $\Hom_R(-, M)$ is exact.
axiom injective (M : Module R) : Prop
-- An $R$-module $M$ is flat if the functor $(-) \otimes_R M$ is exact.
axiom flat (M : Module R) : Prop
-- A non-zero $R$-module $M$ is simple if it has no non-zero proper submodules.
axiom simple (M : Module R) : Prop
-- An $R$-module $M$ is semisimple if it is isomorphic to a direct sum of simple modules.
axiom semisimple (M : Module R) : Prop
-- An $R$-module $M$ is indecomposable if it cannot be written as the direct sum of two non-zero proper submodules.
axiom indecomposable (M : Module R) : Prop
-- An $R$-module $M$ is faithful if $r \cdot M = 0$ implies 
axiom faithful (M : Module R) : Prop
-- An $R$-module $M$ is torsion-free if $rm = 0$ implies $r = 0$ or $m = 0$, for all $r \in R$ and $m \in M$.
axiom torsion_free (M : Module R) : Prop
/- An $R$-module $M$ is noetherian if it it satisfies the ascending chain condition: for any increasing sequence of submodules
\[ M_1 \subset M_2 \subset M_3 \subset \cdots \]
there exists some $N \in \NN$ such that $M_n = M_N$ for any $n \ge N$. -/
axiom noetherian (M : Module R) : Prop
/- An $R$-module $M$ is noetherian if it satisfies the \textit{descending chain condition}: for any decreasing sequence of submodules
\[ M_1 \supset M_2 \supset M_3 \supset \cdots \]
there exists some $N \in \NN$ such that $M_n = M_N$ for any $n \ge N$. -/
axiom artin (M : Module R) : Prop
end Module

end Math.CommutativeAlgebra
