import GMLAlgebra.Basic
import GMLAlgebra.Category
import GMLAlgebra.Group
import GMLAlgebra.Hom
import GMLAlgebra.Identities
import GMLAlgebra.Monoid
import GMLAlgebra.Rig
import GMLAlgebra.Ring
import GMLAlgebra.Semigroup
import GMLAlgebra.Semiring
import GMLAlgebra.Signatures
import GMLAlgebra.UnitalRig
import GMLAlgebra.UnitalRing
import GMLAlgebra.UnitalSemiring
