name: Generate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6,18 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:nightly
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
      shell: bash

    - name: Build Reservoir
      run: |
        git clone https://github.com/xubaiw/Reservoir.lean/ reservoir
        cd reservoir
        lake build
        cd ..
      shell: bash

    - name: Generate Pages
      run: |
        ./reservoir/build/bin/reservoir generate -i lakes.json -o build/
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages 
        folder: build/
      if:
        ${{github.event_name != 'pull_request'}}
