name: Index

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  index-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:nightly
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
      shell: bash

    - name: Build Reservoir
      run: |
        git clone https://github.com/xubaiw/Reservoir.lean/
        cd Reservoir.lean
        lake build
        cd ..
      shell: bash

    - name: Prospect GitHub
      run: |
        ./build/bin/reservoir -i lakes.json -o build/lakes.json
        rm -rf builds
      shell: bash

    - name: Generate Pages
      run: |
        ./Reservoir.lean/build/bin/reservoir generate -i lakes.json -o build/
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: index.html
        path: build/reservoir/index.html
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages 
        folder: build/
