name: Prospect

on:
  schedule:
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
  push:
    paths:
      - '.github/workflows/**'

jobs:
  prospect:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Install Elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:nightly
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
      shell: bash

    - name: Build Reservoir
      run: |
        git clone https://github.com/xubaiw/Reservoir.lean/
        cd Reservoir.lean
        lake build
        cd ..
      shell: bash

    - name: Prospect GitHub
      run: |
        ./Reservoir.lean/build/bin/reservoir prospect -i lakes.json -o lakes.json
        rm -rf ./Reservoir.lean/
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.12.1
